'use client';
import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import Footer from '@/components/footer';
import Sidebar from '@/components/sidebar';

import { usePathname } from 'next/navigation';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang='en'>
      <body className={inter.className}>
        {pathname == '/' || pathname == '/signup' ? <Header /> : <></>}
        <div className='flex justify-center'>
          {pathname !== '/' &&
          pathname !== '/signup' &&
          pathname !== '/welcome' ? (
            <Sidebar />
          ) : (
            <></>
          )}

          {children}
        </div>

        {pathname == '/' || pathname == '/signup' ? <Footer /> : <></>}
      </body>
    </html>
  );
}
