"use client";
import React, { useState } from "react";
import Image from "next/image";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";

import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [showMenu, setShowMenu] = useState(false);
  const [sidebar, setSideBar] = useState(true);

  return (
    // <html lang="en">
    //   <body className={inter.className}>
    <>
      <div
        className={`  h-60 w-full p-2 bg-gray-400 fixed ${
          showMenu ? "flex flex-col" : "hidden"
        }`}
      >
        <div className="flex  justify-between">
          <Image width={100} height={100} src="/img/bag.png" alt="" />
          <button className="" onClick={() => setShowMenu(false)}>
            X
          </button>
        </div>
        <div className="pt-2">
          <p className="pb-2">Home</p>
          <hr />
          <p className="pb-2">Categories</p>
          <hr />
          <p className="pb-2">Rewards</p>
          <hr />
        </div>
        <div className="pt-3">
          <button className="w-40 text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded-lg text-lg">
            Sign Up
          </button>
        </div>
      </div>

      {pathname == "/" || pathname == "/signup" ? (
        <Header onClick={() => setShowMenu(true)} />
      ) : (
        <></>
      )}

      <div className={`flex`}>
        {/* {pathname !== "/" &&
          pathname !== "/signup" &&
          pathname !== "/shopping" &&
          pathname !== "/detail_pilih" &&
          pathname !== "/welcome" ? (
            <div
              className={`${sidebar ? "flex " : "hidden"} flex justify-center`}>
              <Sidebar />
            </div>
          ) : (
            <></>
          )} */}

        <div className={`${sidebar ? "" : ""} w-screen`}>
          <div className="flex justify-center">
            {/* {pathname !== "/" &&
              pathname !== "/signup" &&
              pathname !== "/shopping" &&
              pathname !== "/detail_pilih" &&
              pathname !== "/welcome" ? (
                <Navbar onClick={() => setSideBar(!sidebar)} />
              ) : (
                <></>
              )} */}
          </div>
          {children}
        </div>
      </div>

      {
        pathname == "/shopping" ||   
        pathname == "/detail_pilih" ||  
        pathname == "/cart" ||  
        pathname == "/succes" ?
         <Footer /> : <></>}
    </>

    //   </body>
    // </html>
  );
}
